### ISSUE TITLE
RF24::write(

### ISSUE THREAD

**Issue by mas2227** [maniacbug/RF24#3]
R24.cpp R24::write()  the line:
   status = read_register(OBSERVE_TX,&observe_tx,1);
should be:
   status = read_register(STATUS);
because your registry status bits gert used on the status:
   while( ! ( status & ( _BV(TX_DS) | _BV(MAX_RT) ) ) && ( millis() - sent_at < timeout ) );
RF24::whatHappened():
   uint8_t status = write_register(STATUS,_BV(RX_DR) | _BV(TX_DS) | _BV(MAX_RT) );
should be:
    uint8_t status = read_register(STATUS);
and reset after:
  // Report to the user what happened
  tx_ok = status & _BV(TX_DS);
  tx_fail = status & _BV(MAX_RT);
  rx_ready = status & _BV(RX_DR);
  status = write_register(STATUS, _BV(TX_DS) | _BV(MAX_RT) );
return;

Michael Spohnholtz

ps great work,just stated learning arduino and  r24 has been a great learning project!  thanks!  You live in my part of the woods, i live in lynnwood wa... small world.

**Comment by maniacbug** [comment]
Thanks for writing.  No, the code is correct.

Have another look at the documentation for read_register(uint8_t,uint8_t*,uint8_t).  It's at http://maniacbug.github.com/RF24/classRF24.html#a56bfead61e647d838cbb5e49def9b6d9

"Returns: Current value of status register."

Glad you found it helpful!
